In [ ]:
import pandas as pd
df = pd.read_excel('data/product.xlsx') # 엑셀을 사용하고 싶으면 설치를 해야함 
# pip install openpyxl
df.columns

Index(['날짜', '판매가', '상품목록', '카테고리'], dtype='object')

In [ ]:
# 부가세포함된 가격 컬럼을 추가
# 소비자가 파생변수를 추가 : 판매가 10%를 추가한 금액
def 소비자가(판매가):
  return 판매가 * 1.1

df['소비자가'] = df['판매가'].apply(소비자가)
df

           날짜    판매가                  상품목록  카테고리     소비자가
0  2022-01-25  67000      7102 Metal Chair   NaN  73700.0
1  2022-01-26  69000      7103 Brass Chair   NaN  75900.0
2  2022-01-27  69000      7103 Brass Chair   NaN  75900.0
3  2022-01-28  69000     7103 Brass Chair    NaN  75900.0
4  2022-01-29  45000  Post Modern Table 34   NaN  49500.0
5  2022-01-30  32000       Wooden Table 34   NaN  35200.0
6  2022-01-31  33000       Wooden Table 36   NaN  36300.0
7  2022-02-01  32000        Glass Table 32   NaN  35200.0
8  2022-02-02  59000      Long Red Mirror    NaN  64900.0
9  2022-02-03  59000       Long Red Mirror   NaN  64900.0
10 2022-02-04  58000     Shimmering Mirror   NaN  63800.0
11 2022-02-05  88000       Blue Frame Sofa   NaN  96800.0
12 2022-02-06  88000       Blue Frame Sofa   NaN  96800.0
13 2022-02-07  88000       Blue Frame Sofa   NaN  96800.0
14 2022-02-08  88000  Leather Cushion Sofa   NaN  96800.0
15 2022-02-08  41000             222335555   NaN  45100.0

In [ ]:
import numpy as np
def get_category(name):
  if 'Chair' in str (name):
    return '의자'
  
df['카테고리'] = df['상품목록'].apply(get_category)
df

KeyError: '상품목록'